//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Objective = new List<Objective>();
        }
    
        public int CategoryId { get; set; }
        public string Category1 { get; set; }
        public Nullable<bool> Visibility { get; set; }
    
        public virtual IList<Objective> Objective { get; set; }
    }
}
