//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int ResourceId { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public string CurrentPosition { get; set; }
        public string AspiringPosition { get; set; }
        public Nullable<int> CurrentPositionID { get; set; }
        public Nullable<int> AspiringPositionID { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string Type { get; set; }
        public Nullable<int> AreaId { get; set; }
    
        public virtual Resource Resource { get; set; }
        public virtual Resource Resource1 { get; set; }
        public virtual Position Position { get; set; }
        public virtual Position Position1 { get; set; }
        public virtual Project Project { get; set; }
        public virtual Area Area { get; set; }
    }
}
