//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralTrainingProgram
    {
        public GeneralTrainingProgram()
        {
            this.GeneralTrainingProgramDetails = new List<GeneralTrainingProgramDetails>();
            this.GeneralTrainingProgramVideo = new List<GeneralTrainingProgramVideo>();
            this.GeneralTrainingProgramVisits = new List<GeneralTrainingProgramVisits>();
        }
    
        public int IdGeneralTrainingProgram { get; set; }
        public string Name { get; set; }
        public int Category { get; set; }
        public string Link { get; set; }
        public bool Enabled { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
    
        public virtual TrainingProgramCategory TrainingProgramCategory { get; set; }
        public virtual IList<GeneralTrainingProgramDetails> GeneralTrainingProgramDetails { get; set; }
        public virtual IList<GeneralTrainingProgramVideo> GeneralTrainingProgramVideo { get; set; }
        public virtual IList<GeneralTrainingProgramVisits> GeneralTrainingProgramVisits { get; set; }
    }
}
