//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoalsCompletedTotal
    {
        public string Location { get; set; }
        public string Manager { get; set; }
        public int ResourceId { get; set; }
        public string DomainName { get; set; }
        public string Name { get; set; }
        public Nullable<int> Verified { get; set; }
        public int TillThisMonth { get; set; }
    }
}
