//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groups
    {
        public Groups()
        {
            this.Group_SectionAccess = new List<Group_SectionAccess>();
            this.RankCatalog = new List<RankCatalog>();
        }
    
        public int GroupId { get; set; }
        public string GroupName { get; set; }
    
        public virtual IList<Group_SectionAccess> Group_SectionAccess { get; set; }
        public virtual IList<RankCatalog> RankCatalog { get; set; }
    }
}
