//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeyThrusts
    {
        public int KeyThrustsId { get; set; }
        public int OnePagePlanId { get; set; }
        public string KeyThrust { get; set; }
    
        public virtual OnePagePlan OnePagePlan { get; set; }
    }
}
