//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPI
    {
        public int KpiID { get; set; }
        public int QuaterlyPrioritiesID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string Result { get; set; }
        public string Comment { get; set; }
        public int RankID { get; set; }
    
        public virtual QuarterlyPriorities QuarterlyPriorities { get; set; }
        public virtual RankCatalog RankCatalog { get; set; }
    }
}
