//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.Resources = new List<Resource>();
            this.GeneralTrainingProgramVideo = new List<GeneralTrainingProgramVideo>();
            this.TrainingProgramVideo = new List<TrainingProgramVideo>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string abbreviation { get; set; }
    
        public virtual IList<Resource> Resources { get; set; }
        public virtual IList<GeneralTrainingProgramVideo> GeneralTrainingProgramVideo { get; set; }
        public virtual IList<TrainingProgramVideo> TrainingProgramVideo { get; set; }
    }
}
