//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objective
    {
        public Objective()
        {
            this.GoalTracking = new List<GoalTracking>();
        }
    
        public int ObjectiveId { get; set; }
        public string Objective1 { get; set; }
        public int ResourceId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Quarter { get; set; }
        public Nullable<int> Progress { get; set; }
        public Nullable<bool> Duplicated { get; set; }
    
        public virtual IList<GoalTracking> GoalTracking { get; set; }
        public virtual Resource Resource { get; set; }
        public virtual Category Category { get; set; }
        public virtual ProgressEnum ProgressEnum { get; set; }
    }
}
