//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnePagePlan
    {
        public OnePagePlan()
        {
            this.KeyThrusts = new List<KeyThrusts>();
            this.AnnualPriorities = new List<AnnualPriorities>();
            this.QuarterlyPriorities = new List<QuarterlyPriorities>();
        }
    
        public int OnePagePlanId { get; set; }
        public Nullable<int> Quarter { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> month1_CoreValueId { get; set; }
        public Nullable<int> month2_CoreValueId { get; set; }
        public Nullable<int> month3_CoreValueId { get; set; }
        public string SG { get; set; }
        public string G { get; set; }
        public string R { get; set; }
        public int ResourceId { get; set; }
        public int QuarterId { get; set; }
        public string Y { get; set; }
    
        public virtual IList<KeyThrusts> KeyThrusts { get; set; }
        public virtual Resource Resource { get; set; }
        public virtual IList<AnnualPriorities> AnnualPriorities { get; set; }
        public virtual IList<QuarterlyPriorities> QuarterlyPriorities { get; set; }
        public virtual Quarter Quarter1 { get; set; }
    }
}
