//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgressEnum
    {
        public ProgressEnum()
        {
            this.GoalTrackings = new List<GoalTracking>();
            this.TrainingProgramDetails = new List<TrainingProgramDetails>();
            this.GeneralTrainingProgramDetails = new List<GeneralTrainingProgramDetails>();
            this.TrainingProgramOnDemandDetails = new List<TrainingProgramOnDemandDetails>();
            this.Objective = new List<Objective>();
        }
    
        public int Id { get; set; }
        public string Label { get; set; }
    
        public virtual IList<GoalTracking> GoalTrackings { get; set; }
        public virtual IList<TrainingProgramDetails> TrainingProgramDetails { get; set; }
        public virtual IList<GeneralTrainingProgramDetails> GeneralTrainingProgramDetails { get; set; }
        public virtual IList<TrainingProgramOnDemandDetails> TrainingProgramOnDemandDetails { get; set; }
        public virtual IList<Objective> Objective { get; set; }
    }
}
