//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuarterlyActions
    {
        public int QuarterlyActionId { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> KeyIniciative { get; set; }
        public string Outcome { get; set; }
        public Nullable<int> QuarterlyPrioritiesId { get; set; }
    
        public virtual QuarterlyPriorities QuarterlyPriorities { get; set; }
    }
}
