//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quarter
    {
        public Quarter()
        {
            this.OnePagePlan = new List<OnePagePlan>();
            this.QuarterlyPriorities = new List<QuarterlyPriorities>();
        }
    
        public int QuarterId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Comment { get; set; }
    
        public virtual IList<OnePagePlan> OnePagePlan { get; set; }
        public virtual IList<QuarterlyPriorities> QuarterlyPriorities { get; set; }
    }
}
