//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuarterlyPriorities
    {
        public QuarterlyPriorities()
        {
            this.QuarterlyActions = new List<QuarterlyActions>();
            this.ValuesInfusion = new List<ValuesInfusion>();
            this.PersonalDevelopment = new List<PersonalDevelopment>();
            this.StrategicPriority = new List<StrategicPriority>();
            this.KPI = new List<KPI>();
        }
    
        public int QuarterlyPrioritiesId { get; set; }
        public Nullable<int> Quarter { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> ResourceId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> OnePagePlanId { get; set; }
        public string KeyIssue { get; set; }
        public string ClosingComment { get; set; }
        public string CEOComment { get; set; }
        public string ManagerComment { get; set; }
        public int QuarterId { get; set; }
    
        public virtual OnePagePlan OnePagePlan { get; set; }
        public virtual IList<QuarterlyActions> QuarterlyActions { get; set; }
        public virtual IList<ValuesInfusion> ValuesInfusion { get; set; }
        public virtual IList<PersonalDevelopment> PersonalDevelopment { get; set; }
        public virtual Quarter Quarter1 { get; set; }
        public virtual IList<StrategicPriority> StrategicPriority { get; set; }
        public virtual IList<KPI> KPI { get; set; }
    }
}
