//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.QuestionResponse = new List<QuestionResponse>();
            this.SurveyResponse = new List<SurveyResponse>();
        }
    
        public int QuestionId { get; set; }
        public int SurveyId { get; set; }
        public string Text { get; set; }
        public System.DateTime Updated { get; set; }
        public int Sequence { get; set; }
        public int QuestionType { get; set; }
        public Nullable<int> QuestionChild { get; set; }
        public Nullable<int> Required { get; set; }
        public Nullable<int> DisplayWhenValue { get; set; }
        public Nullable<int> VisibleForEmployee { get; set; }
    
        public virtual IList<QuestionResponse> QuestionResponse { get; set; }
        public virtual Survey Survey { get; set; }
        public virtual IList<SurveyResponse> SurveyResponse { get; set; }
    }
}
