//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionResponse
    {
        public int QuestionId { get; set; }
        public int ResponseId { get; set; }
        public int QuestionResponseId { get; set; }
    
        public virtual Response Response { get; set; }
        public virtual Question Question { get; set; }
    }
}
