//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class RankTypeCatalog
    {
        public RankTypeCatalog()
        {
            this.RankCatalog = new List<RankCatalog>();
        }
    
        public byte RankTypeID { get; set; }
        public string TypeName { get; set; }
        public string Comments { get; set; }
    
        public virtual IList<RankCatalog> RankCatalog { get; set; }
    }
}
