//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public Resource()
        {
            this.GoalTrackings = new List<GoalTracking>();
            this.Objective = new List<Objective>();
            this.Employees = new List<Employee>();
            this.TrainingProgramDetails = new List<TrainingProgramDetails>();
            this.GeneralTrainingProgramDetails = new List<GeneralTrainingProgramDetails>();
            this.TrainingProgramOnDemandDetails = new List<TrainingProgramOnDemandDetails>();
            this.GeneralTrainingProgramVisits = new List<GeneralTrainingProgramVisits>();
            this.TrainingProgramOnDemandVisits = new List<TrainingProgramOnDemandVisits>();
            this.TrainingProgramVisits = new List<TrainingProgramVisits>();
            this.TDURedeem = new List<TDURedeem>();
            this.TDUReward = new List<TDUReward>();
            this.SurveyResource = new List<SurveyResource>();
            this.SurveyResponse = new List<SurveyResponse>();
            this.OnePagePlan = new List<OnePagePlan>();
        }
    
        public int ResourceId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public int RolId { get; set; }
        public string DomainName { get; set; }
        public System.DateTime LastLogin { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> ActiveDirectoryId { get; set; }
        public Nullable<int> IsEnable { get; set; }
    
        public virtual IList<GoalTracking> GoalTrackings { get; set; }
        public virtual Location Location { get; set; }
        public virtual IList<Objective> Objective { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual IList<Employee> Employees { get; set; }
        public virtual IList<TrainingProgramDetails> TrainingProgramDetails { get; set; }
        public virtual IList<GeneralTrainingProgramDetails> GeneralTrainingProgramDetails { get; set; }
        public virtual IList<TrainingProgramOnDemandDetails> TrainingProgramOnDemandDetails { get; set; }
        public virtual IList<GeneralTrainingProgramVisits> GeneralTrainingProgramVisits { get; set; }
        public virtual IList<TrainingProgramOnDemandVisits> TrainingProgramOnDemandVisits { get; set; }
        public virtual IList<TrainingProgramVisits> TrainingProgramVisits { get; set; }
        public virtual IList<TDURedeem> TDURedeem { get; set; }
        public virtual IList<TDUReward> TDUReward { get; set; }
        public virtual IList<SurveyResource> SurveyResource { get; set; }
        public virtual IList<SurveyResponse> SurveyResponse { get; set; }
        public virtual IList<OnePagePlan> OnePagePlan { get; set; }
    }
}
