//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suggestions
    {
        public int SuggestionId { get; set; }
        public int PositionId { get; set; }
        public int TechnologyId { get; set; }
        public string Source { get; set; }
        public int LevelId { get; set; }
        public string Topic { get; set; }
        public Nullable<int> AreaId { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual Technologies Technologies { get; set; }
        public virtual Level Level { get; set; }
        public virtual Area Area { get; set; }
    }
}
