//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyResource
    {
        public SurveyResource()
        {
            this.SurveyResponse = new List<SurveyResponse>();
        }
    
        public int SurveyResourceId { get; set; }
        public int ResourceId { get; set; }
        public int SurveyId { get; set; }
        public System.DateTime DateAnswered { get; set; }
        public int SurveyType { get; set; }
        public Nullable<int> ResourceEvaluatedId { get; set; }
    
        public virtual Resource Resource { get; set; }
        public virtual Survey Survey { get; set; }
        public virtual IList<SurveyResponse> SurveyResponse { get; set; }
    }
}
