//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDUReward
    {
        public TDUReward()
        {
            this.TDURedeem = new List<TDURedeem>();
        }
    
        public int TDURewardId { get; set; }
        public int resourceId { get; set; }
        public int StartingQuarter { get; set; }
        public int EndingQuarter { get; set; }
        public int StartingYear { get; set; }
        public int EndingYear { get; set; }
        public int TotalTDUReward { get; set; }
        public bool Redeemed { get; set; }
        public Nullable<System.DateTime> DateRedeemed { get; set; }
        public bool Paid { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
        public int ValidForQuarters { get; set; }
        public System.DateTime DatetoLoseValidity { get; set; }
    
        public virtual Resource Resource { get; set; }
        public virtual IList<TDURedeem> TDURedeem { get; set; }
    }
}
