//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Threshold
    {
        public int ThresholdId { get; set; }
        public int KpiID { get; set; }
        public int RankID { get; set; }
        public decimal Value { get; set; }
    
        public virtual RankCatalog RankCatalog { get; set; }
    }
}
