//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingCategory
    {
        public TrainingCategory()
        {
            this.GoalTracking = new List<GoalTracking>();
        }
    
        public int TrainingCategoryId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> TDU { get; set; }
        public Nullable<int> MaxTDU { get; set; }
    
        public virtual IList<GoalTracking> GoalTracking { get; set; }
        public virtual TrainingCategory TrainingCategory1 { get; set; }
        public virtual TrainingCategory TrainingCategory2 { get; set; }
    }
}
