//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingProgramOnDemandDetails
    {
        public int IdTrainingProgramOnDemandDetails { get; set; }
        public int IdTrainingProgramOnDemand { get; set; }
        public int Status { get; set; }
        public int ResourceId { get; set; }
    
        public virtual Resource Resource { get; set; }
        public virtual TrainingProgramOnDemand TrainingProgramOnDemand { get; set; }
        public virtual ProgressEnum ProgressEnum { get; set; }
    }
}
