//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingProgramVisitsView
    {
        public string Name { get; set; }
        public string Resource { get; set; }
        public Nullable<int> Visits { get; set; }
        public System.DateTime VisitDate { get; set; }
        public string Category { get; set; }
    }
}
