//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingProgram
    {
        public TrainingProgram()
        {
            this.TrainingProgramDetails = new List<TrainingProgramDetails>();
            this.TrainingProgramVideo = new List<TrainingProgramVideo>();
            this.TrainingProgramVisits = new List<TrainingProgramVisits>();
        }
    
        public int IdTrainingProgram { get; set; }
        public string Name { get; set; }
        public int Position { get; set; }
        public int Category { get; set; }
        public string Link { get; set; }
        public Nullable<bool> Enable { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
    
        public virtual Position Position1 { get; set; }
        public virtual TrainingProgramCategory TrainingProgramCategory { get; set; }
        public virtual IList<TrainingProgramDetails> TrainingProgramDetails { get; set; }
        public virtual IList<TrainingProgramVideo> TrainingProgramVideo { get; set; }
        public virtual IList<TrainingProgramVisits> TrainingProgramVisits { get; set; }
    }
}
