//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValuesInfusion
    {
        public int ValuesInfusionId { get; set; }
        public string Value { get; set; }
        public string DefinitionOfDone { get; set; }
        public Nullable<bool> IsDone { get; set; }
        public string Result { get; set; }
        public Nullable<int> QuarterlyPrioritiesId { get; set; }
    
        public virtual QuarterlyPriorities QuarterlyPriorities { get; set; }
    }
}
